packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"
  - "examples/*"

templates:
  - "templates/*"

# Reduciing the risk of installing fresh compromised packages before detected
minimumReleaseAge: 4320 ## 3 days
minimumReleaseAgeExclude:
- '@shopware/*'
- '@typescript/native-preview'
- 'fast-uri' # audit fix, remove after 18.05.2026
- 'astro' # audit fix, remove after 18.05.2026
- 'nitropack' # audit fix, remove after 18.05.2026
- 'devalue' # audit fix, remove after 18.05.2026
- 'nuxt' # audit fix, remove after 20.05.2026
- '@nuxt/schema' # audit fix, remove after 20.05.2026
- 'oxc-minify' # audit fix, remove after 20.05.2026
- '@nuxt/nitro-server' # audit fix, remove after 20.05.2026
- 'oxc-transform' # audit fix, remove after 20.05.2026
- '@nuxt/kit' # audit fix, remove after 20.05.2026
- 'oxc-parser' # audit fix, remove after 20.05.2026
- '@nuxt/vite-builder' # audit fix, remove after 20.05.2026
- 'oxc-babel' # audit fix, remove after 20.05.2026
- '@oxc-project/types' # audit fix, remove after 20.05.2026
- '@oxc-minify/binding-darwin-arm64' # audit fix, remove after 20.05.2026

auditConfig:
  ignoreGhsas:
    - GHSA-92fh-27vv-894w # not vulnerable - https://github.com/unjs/nanotar/issues/59
  ignoreCves:
    # - CVE-2024-43788
    - CVE-2025-68458 # webpack issue, not affected
    - CVE-2025-68157 # webpack issue, not affected
    - CVE-2024-43788 # webpack issue, not affected
