packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"
  - "examples/*"

templates:
  - "templates/*"

# Reduciing the risk of installing fresh compromised packages before detected
minimumReleaseAge: 4320 ## 3 days
minimumReleaseAgeExclude:
- '@shopware/*'
- 'qs' # security release, remove after 15.01.2026
- 'preact' # security release, remove after 10.01.2026