packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"
  - "examples/*"

templates:
  - "templates/*"

# Reduciing the risk of installing fresh compromised packages before detected
minimumReleaseAge: 4320 ## 3 days
minimumReleaseAgeExclude:
- '@shopware/*'
- 'vercel'
- '@vercel/*'
- 'lodash' # security release, remove after 30.01.2026
- 'lodash-es' # security release, remove after 30.01.2026
- 'tar' # security release, remove after 25.01.2026