packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"
  - "examples/*"

templates:
  - "templates/*"

# Reduciing the risk of installing fresh compromised packages before detected
minimumReleaseAge: 4320 ## 3 days
minimumReleaseAgeExclude:
- '@shopware/*'
- 'axios' # security release, remove after 20.02.2026
- 'tar' # audit fix, remove after 25.02.2026


auditConfig:
  ignoreGhsas:
    - GHSA-92fh-27vv-894w # not vulnerable - https://github.com/unjs/nanotar/issues/59
  ignoreCves:
    # - CVE-2024-43788
    - CVE-2025-68458 # webpack issue, not affected
    - CVE-2025-68157 # webpack issue, not affected
    - CVE-2024-43788 # webpack issue, not affected