packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"
  - "examples/*"

templates:
  - "templates/*"

# Reduciing the risk of installing fresh compromised packages before detected
minimumReleaseAge: 4320 ## 3 days
minimumReleaseAgeExclude:
- '@shopware/*'
- 'vercel'
- '@vercel/*'
- '@isaacs/brace-expansion' # security release, remove after 7.02.2026


auditConfig:
  ignoreCves:
    # - CVE-2024-43788
    - CVE-2025-68458 # webpack issue, not affected
    - CVE-2025-68157 # webpack issue, not affected
    - CVE-2024-43788 # webpack issue, not affected