packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"
  - "examples/*"

templates:
  - "templates/*"

# Reduciing the risk of installing fresh compromised packages before detected
minimumReleaseAge: 4320 ## 3 days
minimumReleaseAgeExclude:
- '@shopware/*'
- '*astro*' # security release, remove after 22.11.2025
- '*vercel*' # security release, remove after 22.11.2025
- 'glob' # security release, remove after 22.11.2025