import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWind3,
} from "unocss";

export default defineConfig({
  theme: {
    colors: {
      "brand-primary": "#D0BCFE",
      "surface-surface": "#141218",
      "outline-outline": "#938F99",
      "outline-outline-variant": "#49454F",
      "outline-outline-primary": "#D0BCFE",
      "outline-outline-disabled": "#A19AA5",
      "outline-outline-focus": "#1722F9",
      "surface-on-surface": "#FFFFFF",
      "states-info": "#99DAFE",
      "states-info-hover": "#8AC2E1",
      "states-info-pressed": "#8AC2E1",
      "states-on-info": "#013957",
      "states-info-container": "#013957",
      "states-on-info-container": "#BBE7FF",
      "surface-surface-variant": "#49454F",
      "states-success": "#BAF2BD",
      "states-success-hover": "#77BA7A",
      "surface-on-surface-variant": "#CAC4D0",
      "surface-surface-disabled": "#4D4850",
      "states-success-pressed": "#77BA7A",
      "surface-on-surface-disabled": "#A19AA5",
      "states-on-success": "#09460C",
      "surface-surface-primary": "#6750A4",
      "surface-on-surface-primary": "#EADDFF",
      "surface-inverse-surface": "#353535",
      "states-success-container": "#0B620F",
      "states-on-success-container": "#C9FFCB",
      "surface-inverse-on-surface": "#FFFFFF",
      "states-warning": "#FFC58A",
      "states-warning-hover": "#FFE1C2",
      "surface-surface-container-lowest": "#0F0D13",
      "states-warning-pressed": "#FFE1C2",
      "surface-surface-container-low": "#1D1B20",
      "surface-surface-container": "#211F26",
      "states-on-warning": "#874400",
      "states-warning-container": "#754719",
      "surface-surface-container-high": "#2B2930",
      "states-on-warning-container": "#FFE1C2",
      "surface-surface-container-highest": "#36343B",
      "surface-background": "#141218",
      "surface-on-background": "#E6E0E9",
      "states-error": "#FFACA8",
      "states-error-hover": "#FFDFDD",
      "states-error-pressed": "#FFDFDD",
      "states-on-error": "#601410",
      "states-error-container": "#8C1D18",
      "states-on-error-container": "#F9DED8",
      "brand-primary-hover": "#AB8CF1",
      "brand-primary-pressed": "#AB8CF1",
      "brand-on-primary": "#381E72",
      "brand-secondary": "#3F2A72",
      "brand-secondary-hover": "#312159",
      "brand-secondary-pressed": "#312159",
      "brand-on-secondary": "#ECE4FF",
      "brand-tertiary": "#373737",
      "brand-tertiary-hover": "#2B2B2B",
      "brand-tertiary-pressed": "#2B2B2B",
      "brand-on-tertiary": "#F7F7F7",
      "opacity-opacity-dark-highest": "#000000BF",
      "fixed-fixed-on-image": "#FFFFFF",
      "other-sale": "#FFACA8",
      "other-shadow": "#000000",
      "opacity-opacity-dark-high": "#00000080",
      "opacity-opacity-dark": "#00000040",
      "opacity-opacity-dark-low": "#0000001E",
      "opacity-opacity-dark-lowest": "#00000014",
      "opacity-opacity-light-highest": "#FFFFFFBF",
      "opacity-opacity-light-high": "#FFFFFF80",
      "opacity-opacity-light": "#FFFFFF40",
      "opacity-opacity-light-low": "#FFFFFF1E",
      "opacity-opacity-light-lowest": "#FFFFFF14",
    },

    fontSize: {
      "scale-01": "12px",
      "scale-02": "14px",
      "scale-03": "16px",
      "scale-04": "20px",
      "scale-05": "24px",
      "scale-06": "32px",
      "scale-07": "40px",
      "scale-08": "48px",
      "scale-09": "64px",
      "scale-10": "72px",
    },
    spacing: {
      "space-margin-l-(1920)": "302px",
      "space-0": "0px",
      "space-2": "2px",
      "space-4": "4px",
      "space-6": "6px",
      "space-8": "8px",
      "space-12": "12px",
      "space-16": "16px",
      "space-24": "24px",
      "space-32": "32px",
      "space-40": "40px",
      "space-48": "48px",
      "space-56": "56px",
      "space-64": "64px",
      "space-80": "80px",
      "space-96": "96px",
      "space-120": "120px",
      "space-160": "160px",
      "space--4": "-4px",
      "space--8": "-8px",
      "space--12": "-12px",
      "space--16": "-16px",
      "space--24": "-24px",
      "radius-0": "0px",
      "radius-2": "2px",
      "radius-4": "4px",
      "radius-6": "6px",
      "radius-8": "8px",
      "radius-10": "10px",
      "radius-12": "12px",
      "radius-400": "16px",
      "radius-round": "9999px",
      "stroke-border-s": "1px",
      "stroke-border-m": "2px",
      "stroke-border-l": "4px",
      "stroke-focus-ring": "2px",
      "blur-100": "4px",
      "depth-0": "0px",
      "depth-100": "4px",
      "depth-200": "8px",
      "depth-400": "16px",
      "depth-800": "32px",
      "depth-1200": "48px",
      "depth-025": "1px",
      "depth-negative-025": "-1px",
      "depth-negative-100": "-4px",
      "depth-negative-200": "-8px",
      "depth-negative-400": "-16px",
      "depth-negative-800": "-32px",
      "depth-negative-1200": "-48px",
      "icon-small": "24px",
      "icon-medium": "32px",
      "icon-large": "40px",
      "space-section-spacing-xs": "var(--space-24)",
      "space-section-spacing-s": "var(--space-40)",
      "space-section-spacing-m": "var(--space-80)",
      "space-section-spacing-l": "var(--space-120)",
      "space-section-spacing-xl": "var(--space-160)",
      "radius-button": "var(--radius-4)",
      "radius-card": "var(--radius-4)",
      "radius-checkbox": "var(--radius-2)",
      "radius-input-field": "var(--radius-8)",
      "radius-overlay": "var(--radius-0)",
    },
    fontFamily: {
      sans: ["Inter", "sans-serif"],
      serif: ["Noto Serif", "serif"],
    },
  },
  presets: [
    presetWind3(),
    presetIcons({
      collections: {
        carbon: () =>
          import("@iconify-json/carbon/icons.json").then((i) => i.default),
      },
    }),
    presetAttributify(),
    presetTypography(),
  ],
  preflights: [
    {
      getCSS: () => `
      body {
        font-family: 'Inter', sans-serif;
      }
      `,
    },
  ],
});
