import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWind3,
} from "unocss";

export default defineConfig({
  theme: {
    colors: {
      "brand-primary": "#D0BCFE",
      "surface-surface": "#141218",
      "outline-outline": "#938F99",
      "outline-outline-variant": "#49454F",
      "outline-outline-primary": "#D0BCFE",
      "outline-outline-disabled": "#A19AA5",
      "outline-outline-focus": "#1722F9",
      "surface-on-surface": "#FFFFFF",
      "states-info": "#99DAFE",
      "states-info-hover": "#8AC2E1",
      "states-info-pressed": "#8AC2E1",
      "states-on-info": "#013957",
      "states-info-container": "#013957",
      "states-on-info-container": "#BBE7FF",
      "surface-surface-variant": "#49454F",
      "states-success": "#BAF2BD",
      "states-success-hover": "#77BA7A",
      "surface-on-surface-variant": "#CAC4D0",
      "surface-surface-disabled": "#4D4850",
      "states-success-pressed": "#77BA7A",
      "surface-on-surface-disabled": "#A19AA5",
      "states-on-success": "#09460C",
      "surface-surface-primary": "#6750A4",
      "surface-on-surface-primary": "#EADDFF",
      "surface-inverse-surface": "#353535",
      "states-success-container": "#0B620F",
      "states-on-success-container": "#C9FFCB",
      "surface-inverse-on-surface": "#FFFFFF",
      "states-warning": "#FFC58A",
      "states-warning-hover": "#FFE1C2",
      "surface-surface-container-lowest": "#0F0D13",
      "states-warning-pressed": "#FFE1C2",
      "surface-surface-container-low": "#1D1B20",
      "surface-surface-container": "#211F26",
      "states-on-warning": "#874400",
      "states-warning-container": "#754719",
      "surface-surface-container-high": "#2B2930",
      "states-on-warning-container": "#FFE1C2",
      "surface-surface-container-highest": "#36343B",
      "surface-background": "#141218",
      "surface-on-background": "#E6E0E9",
      "states-error": "#FFACA8",
      "states-error-hover": "#FFDFDD",
      "states-error-pressed": "#FFDFDD",
      "states-on-error": "#601410",
      "states-error-container": "#8C1D18",
      "states-on-error-container": "#F9DED8",
      "brand-primary-hover": "#AB8CF1",
      "brand-primary-pressed": "#AB8CF1",
      "brand-on-primary": "#381E72",
      "brand-secondary": "#3F2A72",
      "brand-secondary-hover": "#312159",
      "brand-secondary-pressed": "#312159",
      "brand-on-secondary": "#ECE4FF",
      "brand-tertiary": "#373737",
      "brand-tertiary-hover": "#2B2B2B",
      "brand-tertiary-pressed": "#2B2B2B",
      "brand-on-tertiary": "#F7F7F7",
      "opacity-opacity-dark-highest": "#000000BF",
      "fixed-fixed-on-image": "#FFFFFF",
      "other-sale": "#FFACA8",
      "other-shadow": "#000000",
      "opacity-opacity-dark-high": "#00000080",
      "opacity-opacity-dark": "#00000040",
      "opacity-opacity-dark-low": "#0000001E",
      "opacity-opacity-dark-lowest": "#00000014",
      "opacity-opacity-light-highest": "#FFFFFFBF",
      "opacity-opacity-light-high": "#FFFFFF80",
      "opacity-opacity-light": "#FFFFFF40",
      "opacity-opacity-light-low": "#FFFFFF1E",
      "opacity-opacity-light-lowest": "#FFFFFF14",
    },
    spacing: {
      "device-width": "1200px",
      scale: "1px",
      "root-font-size": "16px",
      "font-size-scale-01": "12px",
      "font-size-scale-02": "14px",
      "font-size-scale-03": "16px",
      "font-size-scale-04": "20px",
      "font-size-scale-05": "24px",
      "font-size-scale-06": "32px",
      "font-size-scale-07": "40px",
      "font-size-scale-08": "48px",
      "font-size-scale-09": "64px",
      "font-size-scale-10": "72px",
    },
    fontFamily: {
      sans: ["Inter", "sans-serif"],
      serif: ["Noto Serif", "serif"],
    },
  },
  presets: [
    presetWind3(),
    presetIcons({
      collections: {
        carbon: () =>
          import("@iconify-json/carbon/icons.json").then((i) => i.default),
      },
    }),
    presetAttributify(),
    presetTypography(),
  ],
  preflights: [
    {
      getCSS: () => `
      body {
        font-family: 'Inter', sans-serif;
      }
      `,
    },
  ],
});
