name: Feature request
description: Suggest an idea for this project
labels: [needs-triage]
body:
- type: markdown
  id: feature-description
  attributes:
    label: Describe the feature
    description: A description of the feature you are requesting.
    placeholder: Feature description
  validations:
    required: true
- type: markdown
  attributes:
    label: WHY do we need that?
    description: Provide the main reason for this feature to be implemented.
  validations:
    required: true
- type: markdown
  attributes:
    label: Acceptance Criteria
    description: Describe shortly in points the main criteria to be met in order to fulfill this request.
  validations:
    required: true
- type: checkboxes
  id: additional-info
  attributes:
    label: Additional information
    description: Additional information that helps us decide how to proceed.
    options:
      - label: I want to implement this feature.
- type: checkboxes
  id: required-info
  attributes:
    label: Checks
    description: Before submitting, please make sure you do the following
    options:
      - label: Check existing [discussions](https://github.com/shopware/frontends/discussions) and [issues](https://github.com/shopware/frontends/issues).
        required: true
