name: 🚀 Feature request
description: Suggest an idea for this project
labels: ["pending triage"]
body:
- type: textarea
  id: feature-description
  attributes:
    label: Describe the feature
    description: A description of the feature you are requesting.
    placeholder: Feature description
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A brief description of the feature you are requesting. Please mention use cases, possible solutions and alternatives. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: Describe shortly in points the main criteria to be met in order to fulfill this request.
  validations:
    required: false
- type: checkboxes
  id: additional-info
  attributes:
    label: Additional information
    description: Additional information that helps us decide how to proceed.
    options:
      - label: Would you be willing to help implement this feature?
- type: checkboxes
  id: required-info
  attributes:
    label: Checks
    description: Before submitting, please make sure you do the following
    options:
      - label: Check existing [discussions](https://github.com/shopware/frontends/discussions) and [issues](https://github.com/shopware/frontends/issues).
        required: true
