import type { Customer } from "../../checkout/customer/Customer";
import type { CustomerGroup } from "../../checkout/customer/CustomerGroup";
import type { DocumentBaseConfigDefinition } from "../../checkout/document/DocumentBaseConfigDefinition";
import type { Order } from "../../checkout/order/Order";
import type { PaymentMethod } from "../../checkout/payment/PaymentMethod";
import type { PromotionSalesChannel } from "../../checkout/promotion/PromotionSalesChannel";
import type { ShippingMethod } from "../../checkout/shipping/ShippingMethod";
import type { ShippingMethodPrice } from "../../checkout/shipping/ShippingMethodPrice";
import type { CustomFields } from "../../common/CustomField";
import type { Category } from "../../content/category/Category";
import type { MailHeaderFooter } from "../../content/mail-template/MailHeaderFooter";
import type { MailTemplateSalesChannel } from "../../content/mail-template/MailTemplateSalesChannel";
import type { NewsletterRecipient } from "../../content/newsletter/NewsletterRecipient";
import type { ProductReview } from "../../content/product/ProductReview";
import type { ProductVisibility } from "../../content/product/ProductVisibility";
import type { Language } from "../../framework/language/Language";
import type { Country } from "../country/Country";
import type { Currency } from "../currency/Currency";
import type { CurrencyTranslation } from "../currency/CurrencyTranslation";
import type { NumberRangeSalesChannel } from "../number-range/NumberRangeSalesChannel";
import type { SystemConfig } from "../system-config/SystemConfig";
import type { SalesChannelDomain } from "./SalesChannelDomain";
import type { SalesChannelTranslation } from "./SalesChannelTranslation";
import type { SalesChannelType } from "./SalesChannelType";

/**
 * @public
 */
export type SalesChannel = {
  typeId: string;
  languageId: string;
  currencyId: string;
  paymentMethodId: string;
  shippingMethodId: string;
  countryId: string;
  navigationCategoryId: string;
  footerCategoryId: string | null;
  serviceCategoryId: string | null;
  name: string | null;
  shortName: string | null;
  accessKey: string;
  currencies: CurrencyTranslation[] | null;
  languages: Language[] | null;
  configuration: [] | null;
  active: boolean;
  type: SalesChannelType | null;
  currency: Currency | null;
  language: Language | null;
  paymentMethod: PaymentMethod | null;
  shippingMethod: ShippingMethodPrice | null;
  country: Country | null;
  orders: Order[] | null;
  customers: Customer[] | null;
  countries: Country[] | null;
  paymentMethods: PaymentMethod[] | null;
  shippingMethods: ShippingMethod[] | null;
  translations: SalesChannelTranslation[] | null;
  domains: SalesChannelDomain[] | null;
  systemConfigs: SystemConfig[] | null;
  customFields: CustomFields;
  navigationCategory: Category | null;
  footerCategory: Category | null;
  serviceCategory: Category | null;
  productVisibilities: ProductVisibility[] | null;
  mailTemplates: MailTemplateSalesChannel[] | null;
  mailHeaderFooterId: string | null;
  numberRangeSalesChannels: NumberRangeSalesChannel[] | null;
  mailHeaderFooter: MailHeaderFooter | null;
  customerGroupId: string | null;
  customerGroup: CustomerGroup | null;
  newsletterRecipients: NewsletterRecipient[] | null;
  promotionSalesChannels: PromotionSalesChannel[] | null;
  documentBaseConfigSalesChannels: DocumentBaseConfigDefinition | null;
  productReviews: ProductReview[] | null;
};
