import { createAPIClient } from "@shopware/api-client";
// You can pick types of your current API version, the default one:
import type { operations } from "@shopware/api-client/store-api-types";
// or - RECOMMENDED - your types generated by [@shopware/api-gen](https://www.npmjs.com/package/@shopware/api-gen) CLI:
// import type { operations } from "./api-types/storeApiTypes";

export async function setupExample() {
  const shopwareEndpoint = "https://demo-frontends.shopware.store/store-api";
  const accessToken = "SWSCBHFSNTVMAWNZDNFKSHLAYW";
  
  const apiClient = createAPIClient<operations>({
    baseURL: shopwareEndpoint,
    accessToken: accessToken,
  });

  const loadContextButton = document?.querySelector("#loadContext");

  if (loadContextButton) {
    loadContextButton.addEventListener("click", async () => {
      const contextResult = await apiClient.invoke("readContext get /context");

      const resultContainer = document?.querySelector("#result");
      if (resultContainer) {
        resultContainer.innerHTML = JSON.stringify(contextResult.data, null, 2);
      }
    });
  }
}
