import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWind3,
} from "unocss";

export default defineConfig({
  theme: {
    colors: {
      "brand-primary": "#543B95",
      "surface-surface": "#FFFFFF",
      "outline-outline": "#79747E",
      "outline-outline-variant": "#CAC4D0",
      "outline-outline-primary": "#543B95",
      "outline-outline-disabled": "#9893A6",
      "outline-outline-focus": "#1722F9",
      "surface-on-surface": "#1D1B20",
      "states-info": "#0288D1",
      "states-info-hover": "#0275B4",
      "states-info-pressed": "#0275B4",
      "states-on-info": "#FFFFFF",
      "states-info-container": "#BBE7FF",
      "states-on-info-container": "#013957",
      "surface-surface-variant": "#FBF6FF",
      "states-success": "#15B31C",
      "states-success-hover": "#108C16",
      "surface-on-surface-variant": "#696470",
      "surface-surface-disabled": "#E8E8E8",
      "states-success-pressed": "#108C16",
      "surface-on-surface-disabled": "#9893A6",
      "states-on-success": "#FFFFFF",
      "surface-surface-primary": "#D0BCFF",
      "surface-on-surface-primary": "#3A276A",
      "surface-inverse-surface": "#322F35",
      "states-success-container": "#C9FFCB",
      "states-on-success-container": "#09480C",
      "surface-inverse-on-surface": "#FFFFFF",
      "states-warning": "#F57C00",
      "states-warning-hover": "#C26200",
      "surface-surface-container-lowest": "#FFFFFF",
      "states-warning-pressed": "#C26200",
      "surface-surface-container-low": "#F7F2FA",
      "surface-surface-container": "#F3EDF7",
      "states-on-warning": "#FFFFFF",
      "states-warning-container": "#FFE1C2",
      "surface-surface-container-high": "#ECE6F0",
      "states-on-warning-container": "#874400",
      "surface-surface-container-highest": "#E6E0E9",
      "surface-background": "#FFFFFF",
      "surface-on-background": "#1D1B20",
      "states-error": "#D12D24",
      "states-error-hover": "#AB251D",
      "states-error-pressed": "#AB251D",
      "states-on-error": "#FFFFFF",
      "states-error-container": "#F9DED8",
      "states-on-error-container": "#852221",
      "brand-primary-hover": "#45317A",
      "brand-primary-pressed": "#45317A",
      "brand-on-primary": "#FFFFFF",
      "brand-secondary": "#E1D5FF",
      "brand-secondary-hover": "#D0BCFC",
      "brand-secondary-pressed": "#D0BCFC",
      "brand-on-secondary": "#3A276A",
      "brand-tertiary": "#F1F1F1",
      "brand-tertiary-hover": "#E3E3E3",
      "brand-tertiary-pressed": "#E3E3E3",
      "brand-on-tertiary": "#1D1B20",
      "opacity-opacity-dark-highest": "#000000BF",
      "fixed-fixed-on-image": "#FFFFFF",
      "other-sale": "#D12D24",
      "other-shadow": "#000000",
      "opacity-opacity-dark-high": "#00000080",
      "opacity-opacity-dark": "#0000004D",
      "opacity-opacity-dark-low": "#0000001E",
      "opacity-opacity-dark-lowest": "#00000014",
      "opacity-opacity-light-highest": "#FFFFFFBF",
      "opacity-opacity-light-high": "#FFFFFF80",
      "opacity-opacity-light": "#FFFFFF40",
      "opacity-opacity-light-low": "#FFFFFF1E",
      "opacity-opacity-light-lowest": "#FFFFFF14",
    },

    fontSize: {
      "scale-01": "12px",
      "scale-02": "14px",
      "scale-03": "16px",
      "scale-04": "20px",
      "scale-05": "24px",
      "scale-06": "32px",
      "scale-07": "40px",
      "scale-08": "48px",
      "scale-09": "64px",
      "scale-10": "72px",
    },

    fontFamily: {
      sans: ["Inter", "sans-serif"],
      serif: ["Noto Serif", "serif"],
    },
  },
  presets: [
    presetWind3(),
    presetIcons({
      collections: {
        carbon: () =>
          import("@iconify-json/carbon/icons.json").then((i) => i.default),
      },
    }),
    presetAttributify(),
    presetTypography(),
  ],
  preflights: [
    {
      getCSS: () => `
      body {
        font-family: 'Inter', sans-serif;
      }
      `,
    },
  ],
});
