name: Code examples

run-name: Playwright is testing code examples 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
jobs:
  run-code_examples-tests:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install dependencies with Playwright
        run: |
          pnpm playwright install --with-deps

      - name: Run tests
        run: |
          cd apps/e2e-tests
          pnpm test:examples
