name: Lighthouse CI
run-name: run Lighthouse CI 🚀
on:
  workflow_dispatch:
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            "https://frontends-demo.vercel.app/"
            "https://frontends-demo.vercel.app/Products/"
            "https://frontends-demo.vercel.app/Summer-BBQ/"
          configPath: "./lighthouserc.js"
