name: Lighthouse CI
run-name: run Lighthouse CI 🚀
on:
  workflow_dispatch:
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            "https://frontends-demo.vercel.app/"
            "https://frontends-demo.vercel.app/Products/"
            "https://frontends-demo.vercel.app/Summer-BBQ/"
          configPath: "./lighthouserc.js"
