name: Package Previews

on:
  pull_request:
    types: [labeled]

jobs:
  publish-previews:
    if: github.event.label.name == 'publish-pkg-preview'
    name: Publish Package Previews
    permissions:
      contents: read
      issues: read
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build packages
        run: pnpm build --filter='./packages/*'

      - name: Publish package previews
        run: npx pkg-pr-new publish './packages/api-client' './packages/api-gen' './packages/cms-base-layer' './packages/composables' './packages/helpers' './packages/nuxt-module'
